# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.proof_controller_api import ProofControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProofControllerApi(unittest.TestCase):
    """ProofControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.proof_controller_api.ProofControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_licences_using_get(self):
        """Test case for get_licences_using_get

        A list of licences available  # noqa: E501
        """
        pass

    def test_get_proof_json_using_get(self):
        """Test case for get_proof_json_using_get

        A proof json for a given proof  # noqa: E501
        """
        pass

    def test_get_proof_request_using_get(self):
        """Test case for get_proof_request_using_get

        getProofRequest  # noqa: E501
        """
        pass

    def test_get_proofs_using_get(self):
        """Test case for get_proofs_using_get

        A list of available proofs for a licence  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
