# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.prover_controller_api import ProverControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProverControllerApi(unittest.TestCase):
    """ProverControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.prover_controller_api.ProverControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prover_get_default_credentials_using_get(self):
        """Test case for prover_get_default_credentials_using_get

        Creates a proof request for the prover stored on the file system S3  # noqa: E501
        """
        pass

    def test_prover_get_proof_credentials_using_get(self):
        """Test case for prover_get_proof_credentials_using_get

        proverGetProofCredentials  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
