# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ic_hack_controller_api import IcHackControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIcHackControllerApi(unittest.TestCase):
    """IcHackControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ic_hack_controller_api.IcHackControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_new_user_id_using_post(self):
        """Test case for create_new_user_id_using_post

        createNewUserID  # noqa: E501
        """
        pass

    def test_create_new_user_wallet_using_post(self):
        """Test case for create_new_user_wallet_using_post

        createNewUserWallet  # noqa: E501
        """
        pass

    def test_get_account_id_using_get(self):
        """Test case for get_account_id_using_get

        getAccountID  # noqa: E501
        """
        pass

    def test_get_file_using_get(self):
        """Test case for get_file_using_get

        getFile  # noqa: E501
        """
        pass

    def test_verify_proof_from_s3_using_get(self):
        """Test case for verify_proof_from_s3_using_get

        verifyProofFromS3  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
