# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wallet_controller_api import WalletControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWalletControllerApi(unittest.TestCase):
    """WalletControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.wallet_controller_api.WalletControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_close_wallet_using_delete(self):
        """Test case for close_wallet_using_delete

        Closes a wallet inside the distributed ledger, this must be done before another operation can be complete  # noqa: E501
        """
        pass

    def test_create_wallet_using_put(self):
        """Test case for create_wallet_using_put

        Creates a new wallet inside the distributed ledger  # noqa: E501
        """
        pass

    def test_create_wallet_with_did_using_put(self):
        """Test case for create_wallet_with_did_using_put

        Creates a new wallet inside the distributed ledger using a specific DiD  # noqa: E501
        """
        pass

    def test_delete_wallet_using_delete(self):
        """Test case for delete_wallet_using_delete

        Deletes a wallet inside the distributed ledger  # noqa: E501
        """
        pass

    def test_login_using_get(self):
        """Test case for login_using_get

        Logs into a wallet inside the distributed ledger  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
