# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.master_controller_api import MasterControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMasterControllerApi(unittest.TestCase):
    """MasterControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.master_controller_api.MasterControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cred_schema_using_put(self):
        """Test case for create_cred_schema_using_put

        Creates a new credential schema for the Issuer  # noqa: E501
        """
        pass

    def test_create_credential_definition_using_put(self):
        """Test case for create_credential_definition_using_put

        Create a credential definition for the issuer to reference the schema  # noqa: E501
        """
        pass

    def test_create_issuer_using_put(self):
        """Test case for create_issuer_using_put

        Creates a new issuer for the given ID and Key pair  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
