# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ic_hack_airline_controller_api import IcHackAirlineControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIcHackAirlineControllerApi(unittest.TestCase):
    """IcHackAirlineControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ic_hack_airline_controller_api.IcHackAirlineControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_buy_using_get(self):
        """Test case for buy_using_get

        buy  # noqa: E501
        """
        pass

    def test_get_event_list_using_get(self):
        """Test case for get_event_list_using_get

        getEventList  # noqa: E501
        """
        pass

    def test_get_specific_event_using_get(self):
        """Test case for get_specific_event_using_get

        getSpecificEvent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
