# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.verifier_controller_api import VerifierControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVerifierControllerApi(unittest.TestCase):
    """VerifierControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.verifier_controller_api.VerifierControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_verify_proof_from_s3_using_get1(self):
        """Test case for verify_proof_from_s3_using_get1

        Verifies a proof for the verifier using a proof stored on the File System  # noqa: E501
        """
        pass

    def test_verify_proof_using_get(self):
        """Test case for verify_proof_using_get

        Verifies a proof for the verifier  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
