# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.issuer_controller_api import IssuerControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIssuerControllerApi(unittest.TestCase):
    """IssuerControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.issuer_controller_api.IssuerControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_credential_definition_using_put(self):
        """Test case for get_credential_definition_using_put

        getCredentialDefinition  # noqa: E501
        """
        pass

    def test_issuer_create_credentials_using_put(self):
        """Test case for issuer_create_credentials_using_put

        Issues a Driving Licence to a prover  # noqa: E501
        """
        pass

    def test_issuer_create_ticket_credentials_using_put(self):
        """Test case for issuer_create_ticket_credentials_using_put

        Issues a ticket to a prover  # noqa: E501
        """
        pass

    def test_issuer_email_created_credentials_using_put(self):
        """Test case for issuer_email_created_credentials_using_put

        Issues a Driving Licence to a prover, emailing the response  # noqa: E501
        """
        pass

    def test_issuer_email_created_ticket_credentials_using_put(self):
        """Test case for issuer_email_created_ticket_credentials_using_put

        Issues a ticket to a prover, emailing the response  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
