# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EmailInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'master_secret_id': 'str',
        'person_did': 'str'
    }

    attribute_map = {
        'master_secret_id': 'masterSecretId',
        'person_did': 'personDid'
    }

    def __init__(self, master_secret_id=None, person_did=None):  # noqa: E501
        """EmailInfo - a model defined in Swagger"""  # noqa: E501

        self._master_secret_id = None
        self._person_did = None
        self.discriminator = None

        if master_secret_id is not None:
            self.master_secret_id = master_secret_id
        if person_did is not None:
            self.person_did = person_did

    @property
    def master_secret_id(self):
        """Gets the master_secret_id of this EmailInfo.  # noqa: E501


        :return: The master_secret_id of this EmailInfo.  # noqa: E501
        :rtype: str
        """
        return self._master_secret_id

    @master_secret_id.setter
    def master_secret_id(self, master_secret_id):
        """Sets the master_secret_id of this EmailInfo.


        :param master_secret_id: The master_secret_id of this EmailInfo.  # noqa: E501
        :type: str
        """

        self._master_secret_id = master_secret_id

    @property
    def person_did(self):
        """Gets the person_did of this EmailInfo.  # noqa: E501


        :return: The person_did of this EmailInfo.  # noqa: E501
        :rtype: str
        """
        return self._person_did

    @person_did.setter
    def person_did(self, person_did):
        """Sets the person_did of this EmailInfo.


        :param person_did: The person_did of this EmailInfo.  # noqa: E501
        :type: str
        """

        self._person_did = person_did

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmailInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
