# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class VerifierControllerApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def verify_proof_from_s3_using_get1(self, **kwargs):  # noqa: E501
        """Verifies a proof for the verifier using a proof stored on the File System  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.verify_proof_from_s3_using_get1(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str bucket_name: bucketName
        :param str name: name
        :param str object_name: objectName
        :param str proof: proof
        :param str verifier_did: verifierDid
        :param str verifier_wallet_id: verifierWalletId
        :param str verifier_wallet_key: verifierWalletKey
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.verify_proof_from_s3_using_get1_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.verify_proof_from_s3_using_get1_with_http_info(**kwargs)  # noqa: E501
            return data

    def verify_proof_from_s3_using_get1_with_http_info(self, **kwargs):  # noqa: E501
        """Verifies a proof for the verifier using a proof stored on the File System  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.verify_proof_from_s3_using_get1_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str bucket_name: bucketName
        :param str name: name
        :param str object_name: objectName
        :param str proof: proof
        :param str verifier_did: verifierDid
        :param str verifier_wallet_id: verifierWalletId
        :param str verifier_wallet_key: verifierWalletKey
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['bucket_name', 'name', 'object_name', 'proof', 'verifier_did', 'verifier_wallet_id', 'verifier_wallet_key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method verify_proof_from_s3_using_get1" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'bucket_name' in params:
            query_params.append(('bucketName', params['bucket_name']))  # noqa: E501
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501
        if 'object_name' in params:
            query_params.append(('objectName', params['object_name']))  # noqa: E501
        if 'proof' in params:
            query_params.append(('proof', params['proof']))  # noqa: E501
        if 'verifier_did' in params:
            query_params.append(('verifierDid', params['verifier_did']))  # noqa: E501
        if 'verifier_wallet_id' in params:
            query_params.append(('verifierWalletId', params['verifier_wallet_id']))  # noqa: E501
        if 'verifier_wallet_key' in params:
            query_params.append(('verifierWalletKey', params['verifier_wallet_key']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/prove-s3', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def verify_proof_using_get(self, **kwargs):  # noqa: E501
        """Verifies a proof for the verifier  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.verify_proof_using_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cred_def_id:
        :param str cred_def_id2: credDefId
        :param str cred_def_json:
        :param str cred_defs:
        :param str name: name
        :param str proof_json: proofJson
        :param str proof_request_json: proofRequestJson
        :param str schema_id: schemaId
        :param str verifier_did: verifierDid
        :param str verifier_wallet_id: verifierWalletId
        :param str verifier_wallet_key: verifierWalletKey
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.verify_proof_using_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.verify_proof_using_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def verify_proof_using_get_with_http_info(self, **kwargs):  # noqa: E501
        """Verifies a proof for the verifier  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.verify_proof_using_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cred_def_id:
        :param str cred_def_id2: credDefId
        :param str cred_def_json:
        :param str cred_defs:
        :param str name: name
        :param str proof_json: proofJson
        :param str proof_request_json: proofRequestJson
        :param str schema_id: schemaId
        :param str verifier_did: verifierDid
        :param str verifier_wallet_id: verifierWalletId
        :param str verifier_wallet_key: verifierWalletKey
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cred_def_id', 'cred_def_id2', 'cred_def_json', 'cred_defs', 'name', 'proof_json', 'proof_request_json', 'schema_id', 'verifier_did', 'verifier_wallet_id', 'verifier_wallet_key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method verify_proof_using_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'cred_def_id' in params:
            query_params.append(('credDefId', params['cred_def_id']))  # noqa: E501
        if 'cred_def_id2' in params:
            query_params.append(('credDefId', params['cred_def_id2']))  # noqa: E501
        if 'cred_def_json' in params:
            query_params.append(('credDefJson', params['cred_def_json']))  # noqa: E501
        if 'cred_defs' in params:
            query_params.append(('credDefs', params['cred_defs']))  # noqa: E501
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501
        if 'proof_json' in params:
            query_params.append(('proofJson', params['proof_json']))  # noqa: E501
        if 'proof_request_json' in params:
            query_params.append(('proofRequestJson', params['proof_request_json']))  # noqa: E501
        if 'schema_id' in params:
            query_params.append(('schemaId', params['schema_id']))  # noqa: E501
        if 'verifier_did' in params:
            query_params.append(('verifierDid', params['verifier_did']))  # noqa: E501
        if 'verifier_wallet_id' in params:
            query_params.append(('verifierWalletId', params['verifier_wallet_id']))  # noqa: E501
        if 'verifier_wallet_key' in params:
            query_params.append(('verifierWalletKey', params['verifier_wallet_key']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/prove', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
